[workspace]
authors = ["gaozhan <18602912875@163.com>"]
channels = ["conda-forge"]
name = "diary"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
sphinx = "8.2.3.*"
furo = ">=2024.8.6,<2025"
